# Options: testnet, mainnet
net_type = "testnet"

[loki.rpc]
port = 6934
# wallet_address = ""

[eth]
# Go to https://iancoleman.io/bip39/ to generate one
# master_root_key = ""

[btc]
# generate one
# master_root_key = ""
