[package]
name = "blockswap"
version = "0.1.0"
authors = ["Maxim Shishmarev <maxim@loki.network>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "^2"
log = "0.4.0"
log4rs = "*"
tokio = { version = "*", features = ["full"] }
warp = "*"
crossbeam-channel = "^0.4"

[lib]
name = "blockswap"
path = "src/lib.rs"

[[bin]]
name = "vault"
path = "src/bin/vault/main.rs"


[[bin]]
name = "quoter"
path = "src/bin/quoter/main.rs"

[dev-dependencies]
env_logger="*"