[package]
authors = ["Maxim Shishmarev <maxim@loki.network>"]
edition = "2018"
name = "chainflip"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
base58-monero = "0.2"
base64 = "*"
bitcoin = "0.25.2"
bitcoincore-rpc = "0.12.0"
bs58 = "0.3.1"
chainflip-common = { path = "chainflip-common" }
clap = "^2"
config = "^0.10.1"
crossbeam-channel = "^0.4"
env_logger = "0.8"
futures = "0.3.5"
hdwallet = "0.2.5"
hex = "0.4"
itertools = "0.10"
lazy_static = "1.4"
log = "0.4.0"
log4rs = "1.0"
num-bigint = "0.3.0"
parking_lot = "0.11"
rand = "0.8"
regex = "1.4"
reqwest = {version = "^0.10", features = ["json"]}
ring = "0.16"
# Note: this should be the same version as that used by the web3 crate.
secp256k1 = "^0.20"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
tiny-keccak = {version = "^2.0.0", features = ["keccak"]}
tokio = {version = "1.1", features = ["full"]}
uint = "^0.8.5"
uuid = {version = "0.8", features = ["serde", "v4"]}
warp = {version = "*", features = ["tls"]}
web3 = {version = "^0.15.0"}

[dependencies.rusqlite]
features = ["bundled"]
version = "0.21.0"

[lib]
name = "chainflip"
path = "src/lib.rs"

[[bin]]
name = "vault"
path = "src/bin/vault/main.rs"

[[bin]]
name = "quoter"
path = "src/bin/quoter/main.rs"

[[bin]]
name = "loki-playground"
path = "src/bin/loki.rs"

[[bin]]
name = "pool-tool"
path = "src/bin/pool.rs"
