[package]
authors = ["Maxim Shishmarev <maxim@loki.network>"]
edition = "2018"
name = "chainflip"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "*"
base58-monero = "*"
bitcoin = "0.25.1"
bitcoincore-rpc = "0.12.0"
bs58 = "0.3.1"
clap = "^2"
config = "^0.10.1"
crossbeam-channel = "^0.4"
env_logger = "*"
ethereum-tx-sign = "*"
futures = "0.3.5"
hdwallet = "0.2.5"
hex = "*"
itertools = "*"
lazy_static = "*"
log = "0.4.0"
log4rs = "*"
num-bigint = "0.3.0"
parking_lot = "0.11"
rand = "*"
regex = "*"
reqwest = {version = "^0.10", features = ["json"]}
serde = {version = "1.0", features = ["derive"]}
serde_json = "*"
tiny-keccak = {version = "^2.0.0", features = ["keccak"]}
tokio = {version = "*", features = ["full"]}
uint = "^0.8.5"
uuid = {version = "0.8", features = ["serde", "v4"]}
warp = {version = "*", features = ["tls"]}
web3 = {version = "^0.13.0", default-features = false, features = ["http-tls"]}

[dependencies.rusqlite]
features = ["bundled"]
version = "0.21.0"

[lib]
name = "blockswap"
path = "src/lib.rs"

[[bin]]
name = "vault"
path = "src/bin/vault/main.rs"

[[bin]]
name = "quoter"
path = "src/bin/quoter/main.rs"

[[bin]]
name = "loki-playground"
path = "src/bin/loki.rs"
