[package]
name = "blockswap"
version = "0.1.0"
authors = ["Maxim Shishmarev <maxim@loki.network>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "^2"
log = "0.4.0"
log4rs = "*"
tokio = { version = "*", features = ["full"] }
warp = { version = "*", features = ["tls"] }
crossbeam-channel = "^0.4"
serde = { version = "1.0", features = ["derive"]}
serde_json = "*"
rand = "*"
lazy_static = "*"
base58-monero = "*"
bs58 = "0.3.1"
hdwallet = "0.2.5"
reqwest= { version = "^0.10", features = ["json"]}
tiny-keccak = "*"
hex = "*"
async-trait="*"
regex="*"
web3 = { version = "^0.13.0", default-features = false, features = ["http-tls"] }
uuid = { version = "0.8", features = ["serde", "v4"] }
itertools="*"
uint="^0.8.5"
env_logger="*"

[dependencies.rusqlite]
version = "0.21.0"
features = ["bundled"]


[lib]
name = "blockswap"
path = "src/lib.rs"

[[bin]]
name = "vault"
path = "src/bin/vault/main.rs"


[[bin]]
name = "quoter"
path = "src/bin/quoter/main.rs"

[[bin]]
name = "loki-playground"
path = "src/bin/loki.rs"

