[package]
name = "blockswap"
version = "0.1.0"
authors = ["Maxim Shishmarev <maxim@loki.network>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "^2"

[lib]
name = "blockswap"
path = "src/lib.rs"

[[bin]]
name = "witness"
path = "src/bin/witness/main.rs"

[[bin]]
name = "processor"
path = "src/bin/processor/main.rs"

[[bin]]
name = "quoter"
path = "src/bin/quoter/main.rs"