[package]
name = "chainflip-engine"
version = "0.1.0"
authors = ["Kyle Zsembery <zsembery.kyle@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-channel = "0.5.1"
nats = "0.9.12"