[package]
authors = ['Chainflip <https://chainflip.io>']
description = 'Common utilities used by the State Chain and the Chainflip Engine'
edition = '2021'
homepage = 'https://chainflip.io'
license = 'TBC'
name = 'utilities'
repository = 'https://github.com/chainflip-io/chainflip-backend'
version = '0.1.0'

[dependencies]
hex = {version = "0.4.3", default-features = false}
anyhow = {version = '1.0', default-features = false}
jsonrpc-core = "18.0.0"
jsonrpc-core-client = '18.0.0'
predicates = "2.1.1"
mockall = "0.11.0"
futures = "0.3.14"
tokio = {version = "1.13.1", features = ["full"], optional = true}

[features]
default = ['std']
std = [
  'tokio',
  'hex/std',
  'anyhow/std'
]
