[package]
authors = ['Chainflip Team <https://github.com/chainflip-io>']
description = 'FRAME pallet for the FLIP token.'
edition = '2018'
homepage = 'https://chainflip.io'
license = '<TODO>'
name = 'pallet-cf-flip'
repository = 'https://github.com/chainflip-io/chainflip-backend'
version = '0.1.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
# External dependencies
codec = {default-features = false, features = ['derive'], package = 'parity-scale-codec', version = '2.0.0'}

# Internal dependencies
cf-traits = { path = '../../traits', default-features = false }

# Substrate dependencies
frame-benchmarking = {default-features = false, optional = true, version = '3.1.0' }
frame-support = {default-features = false, version = '3.0.0' }
frame-system = {default-features = false, version = '3.0.0' }
pallet-balances = { default-features = false, version = '3.0.0' }

[dev-dependencies]
serde = '1.0.119'
sp-core = {default-features = false, version = '3.0.0' }
sp-io = {default-features = false, version = '3.0.0' }
sp-runtime = {default-features = false, version = '3.0.0' }

[features]
default = ['std']
std = [
    'cf-traits/std',
    'codec/std',
    'frame-support/std',
    'frame-system/std',
    'frame-benchmarking/std',
    'pallet-balances/std',
]
