version: 2
workflows:
  build:
    jobs:
      - build:
          context:
            - ghcr-credentials
jobs:
  build:
    docker:
      - image: ghcr.io/chainflip-io/infrastructure/chainflip-master:latest
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - run: drone lint --trust
