version: 2.1
orbs:
  docker: circleci/docker@1.7.0
workflows:
  chainflip-backend-checks:
    jobs:
      - lint: &context
          context:
            - ghcr-credentials
      - build-rust-base:
          context:
            - dockerhub-credentials

jobs:
  lint:
    docker:
      - image: ghcr.io/chainflip-io/infrastructure/chainflip-master:latest
        auth: &dockerconfig
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - run: drone lint --trusted

  build-rust-base:
    executor: docker/docker
    steps:
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - checkout
      - docker/check:
          docker-username: DOCKER_USERNAME
          registry: ghcr.io
      - docker/build:
          image: ghcr.io/chainflip-io/chainflip-backend/rust-base
          cache_from: ghcr.io/chainflip-io/chainflip-backend/rust-base:latest
          dockerfile: Dockerfile.rust-base
          registry: ghcr.io
      - docker/push:
          digest-path: /tmp/digest.txt
          image: my_repo/orb-test
