workflows:
  version: 2
  chainflip-backend-checks:
    jobs:
      - build: &context
          context:
            - ghcr-credentials
      - build-rust-base:
          context:
            - dockerhub-credentials

jobs:
  lint:
    docker:
      - image: ghcr.io/chainflip-io/infrastructure/chainflip-master:latest
        auth: &dockerconfig
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - run: drone lint --trusted

  build-rust-base:
    docker:
      - image: circleci/golang:1.15
        auth:
          username: tomjohnburton
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - run: |
          TAG=latest
          IMAGE=ghcr.io/chainflip-io/chainflip-backend/rust-base
          docker build --cache-from $IMAGE:$TAG -t $IMAGE:$TAG -f Dockerfile.rust-base .
          echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
          docker push $IMAGE:$TAG
