# Default configurations for the CFE

[message_queue]
# can also be IP
hostname = "localhost"
port = "4222"

[state_chain]
hostname = "localhost"
port = "9944"

[eth]
# TODO: make this 2 hostname and port
url = "localhost:8545"