kind: pipeline
name: build-base-images
type: docker

steps:
  - name: build
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: ghcr.io/chainflip-io/chainflip-infrastructure/rust-base
      dockerfile: Dockerfile.rust-base
      registry: ghcr.io
      tags: latest
      cache_from: ghcr.io/chainflip-io/chainflip-infrastructure/rust-base:latest

trigger:
  branch:
    - main
  event:
    - push

volumes:
  - name: cache
    host:
      path: /mnt/chainflip-build-runner/sccache
node:
  builder: "true"

image_pull_secrets:
  - dockerconfigjson
