- hosts: deb
  tasks:
    - name: Upload debian packages to debian
      ignore_errors: yes
      copy: 
        src: ./files
        dest: /tmp
        directory_mode: yes
    - name: Include all deb files in the repo
      ignore_errors: yes
      shell: 
        cmd: reprepro -b /srv/repos/apt/debian includedeb focal *.deb
        chdir: /tmp
